FROM eclipse-temurin:21-alpine
WORKDIR /app
COPY . /app
RUN --mount=type=secret,id=github_token GITHUB_TOKEN=$(cat /run/secrets/github_token) ./gradlew :batch:bootJar
ENTRYPOINT java $JAVA_OPTS -jar batch/build/libs/snuttev-batch.jar --job.name=${JOB_NAME}
