spring.profiles.default: local

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/snutt?serverTimezone=UTC
    username: snutt
    password: wafflestudio
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: snutt
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: true

---

spring.config.activate.on-profile: dev

secretNames: dev/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host:
      port:
      authentication-database:
      database:

---

spring.config.activate.on-profile: prod

secretNames: prod/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    mongodb:
      host:
      port:
      authentication-database:
      database:
