spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/snutt?serverTimezone=UTC
    username: snutt
    password: wafflestudio
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: snutt
  #      username: snutt
  #      password: snutt

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://wafflestudio-mysql-202107.caxwrw8c4qqq.ap-northeast-2.rds.amazonaws.com/snutt?serverTimezone=UTC
    username: snutt
    password: 237044526e3441d2b7cac45ece763d1a
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: snutt-mongo-dev.wafflestudio.com
      port: 27017
      authentication-database: admin
      database: snutt

---

spring:
  config:
    activate:
      on-profile: prod
