spring.profiles.default: dev

secretNames: dev/snutt-ev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snutt?serverTimezone=UTC
    username: snutt
    password: wafflestudio
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: snutt

---

spring.config.activate.on-profile: dev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: snutt

---

spring.config.activate.on-profile: prod
