spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost/snutt?serverTimezone=UTC
    username: snutt
    password: 237044526e3441d2b7cac45ece763d1a
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
