spring.profiles.default: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snutt?serverTimezone=UTC
    username: snutt
    password: wafflestudio
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  redis:
    host: localhost
    port: 6379
    ttl: 5m
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: snutt
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: true
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC

---

spring.config.activate.on-profile: dev

secretNames: dev/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host:
    port:
    database:
    ttl: 5m
  data:
    mongodb:
      host:
      port:
      authentication-database:
      database:

---

spring.config.activate.on-profile: prod

secretNames: prod/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  redis:
    host:
    port:
    database:
    ttl: 10m
  data:
    mongodb:
      host:
      port:
      authentication-database:
      database: