spring.profiles.default: local

spring:
  main:
    allow-circular-references: true
  config:
    import: application-common.yml
  redis:
    host: localhost
    port: 6379
    ttl: 5m
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: true
  jpa:
    show-sql: true

---

spring.config.activate.on-profile: dev

spring:
  redis:
    host:
    port:
    database:
    ttl: 5m

---

spring.config.activate.on-profile: prod

spring:
  redis:
    host:
    port:
    database:
    ttl: 10m
