spring.profiles.default: local

spring:
  config:
    import: application-core.yml
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: true
    property-naming-strategy: SNAKE_CASE

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:

---

spring.config.activate.on-profile: dev

server:
  tomcat:
    accesslog:
      enabled: false

---

spring.config.activate.on-profile: prod

server:
  tomcat:
    accesslog:
      enabled: false
