spring.profiles.default: local

spring:
  config:
    import: application-core.yml
  mongodb:
    uri: mongodb://localhost:27017/snutt?authSource=admin
  batch:
    job:
      name: ${job.name:EMPTY}
  main:
    web-application-type: none

---

spring.config.activate.on-profile: dev

spring:
  mongodb:
    uri:

---

spring.config.activate.on-profile: prod

spring:
  mongodb:
    uri:
