spring.profiles.default: local

spring:
  config:
    import: application-core.yml
  mongodb:
    host: localhost
    port: 27017
    authentication-database: admin
    database: snutt
  batch:
    job:
      name: ${job.name:EMPTY}
  main:
    web-application-type: none

---

spring.config.activate.on-profile: dev

spring:
  mongodb:
    host:
    port:
    authentication-database:
    database:

---

spring.config.activate.on-profile: prod

spring:
  mongodb:
    host:
    port:
    authentication-database:
    database:
