spring.profiles.default: local
---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      timeout: 3s
      default-ttl: 5m
      repositories:
        enabled: false

logging:
  config: classpath:logback/local.xml

secret-names: dev/snutt-ev

---

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;NON_KEYWORDS=year
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      timeout: 3s
      default-ttl: 5m
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: none

---

spring.config.activate.on-profile: dev

secret-names: dev/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: false
  data:
    redis:
      default-ttl: 5m

---

spring.config.activate.on-profile: prod

secret-names: prod/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: false
  data:
    redis:
      default-ttl: 1h
