spring:
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      timeout: 3s
      default-ttl: 5m
      repositories:
        enabled: false

logging:
  config: classpath:logback/local.xml

oci-vault-secret-ids: ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqafa7scbk7gagxd5gpvdsk276l557wyntv7tcwqeviumha

---

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;NON_KEYWORDS=year
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      timeout: 3s
      default-ttl: 5m
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: none

---

spring.config.activate.on-profile: dev

oci-vault-secret-ids: ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqafa7scbk7gagxd5gpvdsk276l557wyntv7tcwqeviumha

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: false
  data:
    redis:
      default-ttl: 5m

---

spring.config.activate.on-profile: prod

oci-vault-secret-ids: ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqacwytts3muhrtzpf44mq75rvycqdowudm27z433s6htma

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: false
  data:
    redis:
      default-ttl: 1h
