spring.profiles.default: local
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/snutt?serverTimezone=UTC
    username: snutt
    password: wafflestudio
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  redis:
    host: localhost
    port: 6379
    ttl: 5m

---

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;NON_KEYWORDS=year

---

spring.config.activate.on-profile: dev

secretNames: dev/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: false
  redis:
    host:
    port:
    database:
    ttl: 5m

---

spring.config.activate.on-profile: prod

secretNames: prod/snutt-ev

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: false
  redis:
    host:
    port:
    database:
    ttl: 10m
