name: Test CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Initiate Database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE USER 'snutt'@'%' IDENTIFIED BY 'wafflestudio''
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE snutt'
          mysql -uroot -h127.0.0.1 -proot -e 'GRANT ALL PRIVILEGES ON snutt.* TO 'snutt'@'%'

      - name: Run Tests
        run: |
          ./gradlew clean test
